services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DB_USER}
      POSTGRES_DB: ${JOURNEY_DB_NAME}
      POSTGRES_PASSWORD: ${JOURNEY_DB_PASSWD}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      JOURNEY_DB_HOST: db
      JOURNEY_DB_PORT: ${JOURNEY_DB_PORT:-5432}
      JOURNEY_DB_NAME: ${JOURNEY_DB_NAME}
      JOURNEY_DB_USER: ${JOURNEY_DB_USER}
      JOURNEY_DB_PASSWD: ${JOURNEY_DB_PASSWD}
    depends_on:
      - db

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
